"""add table chats

Revision ID: e21a6cf09f1e
Revises: c02678908f74
Create Date: 2026-03-19 23:32:28.634060

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e21a6cf09f1e'
down_revision: Union[str, Sequence[str], None] = 'c02678908f74'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.create_table('chats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('group', 'private', name='chattype'), nullable=False),
    sa.Column('title', sa.String(length=60), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('chatparticipant',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chat_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.Enum('admin', 'base', name='chatparticipanttype'), nullable=False),
    sa.Column('joined_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['chat_id'], ['chats.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # Добавляем с дефолтом, потом убираем дефолт
    op.add_column('users', sa.Column('is_online', sa.Boolean(), nullable=False, server_default='false'))
    op.alter_column('users', 'is_online', server_default=None)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_online')
    op.drop_table('chatparticipant')
    op.drop_table('chats')
    # ### end Alembic commands ###
